name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_DB: symfony_test
          POSTGRES_USER: symfony
          POSTGRES_PASSWORD: symfony
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U symfony"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: docker-compose up -d

    - name: Wait for PostgreSQL
      run: |
        until docker-compose exec db pg_isready -U symfony; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 1
        done

    - name: Install dependencies
      run: docker-compose exec app composer install

    - name: Create test database
      run: docker-compose exec app php bin/console doctrine:database:create --env=test

    - name: Run migrations
      run: docker-compose exec app php bin/console doctrine:migrations:migrate --env=test --no-interaction

    - name: Load fixtures
      run: docker-compose exec app php bin/console doctrine:fixtures:load --env=test --no-interaction

    - name: Run tests
      run: docker-compose exec app vendor/bin/phpunit

    - name: Tear down Docker Compose
      run: docker-compose down