name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Set up Docker Compose
      run: docker-compose up -d

    - name: Install dependencies
      run: docker-compose exec -T app composer install

    - name: Create test database
      run: docker-compose exec -T app php bin/console doctrine:database:create --env=test

    - name: Run migrations
      run: docker-compose exec -T app php bin/console doctrine:migrations:migrate --env=test --no-interaction

    - name: Load fixtures
      run: docker-compose exec -T app php bin/console doctrine:fixtures:load --env=test --no-interaction

    - name: Run tests
      run: docker-compose exec -T app vendor/bin/phpunit

    - name: Tear down Docker Compose
      run: docker-compose down